const AIQuestion = require("../models/AIQuestion");
const { GoogleGenAI } = require("@google/genai");

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY,
});

const getAIQuestions = async (req, res) => {
  try {
    const questions = await AIQuestion.find();

    res.status(200).json(questions);
  } catch (error) {
    console.log("GET AI QUESTIONS ERROR:", error);

    res.status(500).json({
      message: error.message,
    });
  }
};

const generateInterviewQuestions = async (req, res) => {
  try {
    const { role, experience } = req.body;

    if (!role || !experience) {
      return res.status(400).json({
        message: "Role and experience are required",
      });
    }

    const prompt = `
Generate 5 interview questions for:

Role: ${role}
Experience: ${experience}

Rules:
- Technical interview questions only
- One question per line
- No numbering
- No explanations
`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
    });

    const text =
      typeof response.text === "function"
        ? response.text()
        : response.text || "";

    const questions = text
      .split("\n")
      .map((q) => q.trim())
      .filter((q) => q.length > 0);

    if (questions.length === 0) {
      return res.status(500).json({
        message: "No questions generated by AI",
      });
    }

    try {
      for (const question of questions) {
        await AIQuestion.create({
          skill: role,
          question,
        });
      }
    } catch (dbError) {
      console.log("DATABASE SAVE ERROR:");
      console.log(dbError);
    }

    res.status(200).json({
      role,
      experience,
      questions,
    });

  } catch (error) {
    console.log("=================================");
    console.log("AI GENERATION ERROR");
    console.log(error);
    console.log("=================================");

    res.status(500).json({
      message:
        error.message ||
        "Failed to generate questions",
    });
  }
};

module.exports = {
  getAIQuestions,
  generateInterviewQuestions,
};